/**
 * Copyright (c) 2013 Azeem Arshad
 * See the file license.txt for copying permission.
 */

CanvasTestWithFM("ChannelShift", 5, function(canvas, gl, fm, copier) {
    var gradientProgram = new GradientProgram();
    gradientProgram.init(gl);

    var testValues = [
        ["RBG", "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAACDElEQVR4Xu3SQUREYRSG4XsrkYhEIpGIRCKRSEQikSERiUQikYhEIpGIRCKRSMSIRCIRiUQikYhEIpGIRKLbbCJjFk2rd/EufoffOWdxni8Mo68oMwiCjMT7XVP9/afnZ8Z9f7txGEafgiSFMTl46YQqnd5UIU2AfAjCAnkXhAXyJggL5FUQFsiLICyQZ0FYIE+CsEAeBWGBPAjCArkXhAVyJwgL5FYQFsiNICyQa0FYIFeCsEAuBWGBXAjCAjkXhAVyJggL5FQQFsiJICyQY0FYIEeCsEAOBWGBHAjCAtkXhAWyJwgLZFcQFsiOICyQbUFYIFuCsEDigrBANgVhgWwIwgJZF4QFsiYIC2RVEBbIiiAskGVBWCBLgrBAFgVhgSwIwgKZF4QFMicIC2RWEBbIjCAskGlBWCBTgrBAJgVhgUwIwgIZF4QFMiYIC2RUEBbIiCAskGFBWCBDgrBABgVhgQwIwgLpF4QF0icIC6RXEBZIjyAskG5BWCBdgrBAOgVhgXQIwgKJCcICaReEBdImCAukVRAWSIsgLJBmQVggTYKwQBoFYYE0CMICqReEBVInCAukVhAWSI0gLJBqQVggVYKwQCoFYYFUCMICKReEBVImCAukVBAWSIkgLJBiQVggRYKwQAoFYYEUCMICyReEBZInCAskVxAWSI4gLJBsQVggWYKwQEJBQCDfKcdcsh2w+wAAAAAASUVORK5CYII="],
        ["BRG", "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAACBElEQVR4Xu3SQURFYRBA4ftXIo9IJBKJSCQSiUQkEolEJBKJRCISiUQiEok8EolIJBKJSCQSiUQkEolEJBLdXoto0SKtzuIsxjBmZjHfhDh8xFF6FEVpqfiZf6v9p+d7xn1/unGIw7sgX88CeZgUyJsgLJBXQVggL4KwQJ4FYYE8CcICeRSEBfIgCAvkXhAWyJ0gLJBbQVggN4KwQK4FYYFcCcICuRSEBXIhCAvkXBAWyJkgLJBTQVggJ4KwQI4FYYEcCcICORSEBXIgCAtkXxAWyJ4gLJBdQVggO4KwQLYFYYFsCcIC2RSEBbIhCAtkXRAWyJogLJBVQVggK4KwQJYFYYEsCcICSQrCAlkUhAWyIAgLZF4QFsicICyQWUFYIDOCsECmBWGBTAnCApkUhAUyIQgLZFwQFsiYICyQUUFYICOCsECGBWGBDAnCAhkUhAUyIAgLpF8QFkifICyQXkFYID2CsEC6BWGBdAnCAukUhAXSIQgLpF0QFkibICyQVkFYIC2CsECaBWGBNAnCAmkUhAXSIAgLpF4QFkidICyQWkFYIDWCsECqBWGBVAnCAqkUhAVSIQgLpFwQFkiZICyQUkFYICWCsECKBWGBFAnCAikUhAVSIAgLJF8QFkieICyQXEFYIDmCsECyBWGBJARhgWQJwgLJFIQFkiEICyQIAgL5BCorXLLpxtOoAAAAAElFTkSuQmCC"],
        ["BGR", "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAACA0lEQVR4Xu3SQURFYRBA4ftXIo9IJBJ5RCKRSCQi8UQiEYlEIpGIRCKRiEQikUhEIpFIRCKRSCQikUgkIpHoFokWLdLqLM5iDGNmFvNNiN9DHEXpURSlfcbP/FvtPz3fM+77y41D/CbI1yMyHibEr4KwQF4EYYE8C8ICeRKEBfIoCAvkQRAWyL0gLJA7QVggt4KwQG4EYYFcC8ICuRKEBXIpCAvkQhAWyLkgLJAzQVggp4KwQE4EYYEcC8ICORKEBXIoCAvkQBAWyL4gLJA9QVggu4KwQHYEYYFsC8IC2RKEBbIpCAtkQxAWyLogLJA1QVggq4KwQFYEYYEsC8ICWRKEBbIoCAtkQRAWyLwgLJA5QVggs4KwQGYEYYFMC8ICmRKEBTIpCAtkQhAWyLggLJAxQVggo4KwQEYEYYEMC8ICGRKEBTIoCAtkQBAWSL8gLJA+QVggvYKwQHoEYYF0C8IC6RKEBdIpCAukQxAWSLsgLJA2QVggrYKwQFoEYYE0C8ICaRKEBdIoCAskJQgLpEEQFki9ICyQOkFYILWCsEBqBGGBVAvCAqkShAVSKQgLpEIQFki5ICyQMkFYIKWCsEBKBGGBFAvCAkkKwgIpEoQFUigIC6RAEBZIviAskDxBWCC5grBAcgRhgWQLwgJJCMICyRKEBZIpCAskQxAWSBCEBPIB+LJcshRfSW0AAAAASUVORK5CYII="],
        ["GBR", "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAACAUlEQVR4Xu3SQUQGYAyA4e+rRCISiUQiEolEIhGJXyQSkUgkEolIJBKJSCQSiUQkEolEJBKJRCISiUQiEon+OhQdOqTTe3gPM2bbYc/iezImQ0gNIaR8xs/8W+0/Pd8z7vvLjeObIF+PyHiY+CoIC+RFEBbIsyAskCdBWCCPgrBAHgRhgdwLwgK5E4QFcisIC+RGEBbItSAskCtBWCCXgrBALgRhgZwLwgI5E4QFcioIC+REEBbIsSAskCNBWCCHgrBADgRhgewLwgLZE4QFsisIC2RHEBbItiAskC1BWCCbgrBANgRhgawLwgJZE4QFsioIC2RFEBbIsiAskCVBWCCLgrBAFgRhgcwLwgKZE4QFMisIC2RGEBbItCAskClBWCCTgrBAJgRhgYwLwgIZE4QFMioIC2REEBbIsCAskCFBWCCDgrBABgRhgfQLwgLpE4QF0isIC6RHEBZItyAskC5BWCCdgrBAOgRhgbQLwgJpE4QF0ioIC6RFEBZIsyAskCZBWCCNgrBAEoKwQBoEYYHUC8ICqROEBVIrCAukRhAWSLUgLJAqQVgglYKwQCoEYYGUC8ICKROEBVIqCAukRBAWSLEgLJAiQVgghYKwQAoEYYHkC8ICyROEBZIrCAskRxAWSLYgLJAsQVggmYKwQDIEYYGkC8ICSROEBRIFQYF8AMbkXLIklJHOAAAAAElFTkSuQmCC"],
        ["GRB", "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAACAUlEQVR4Xu3SQUSEYRCA4f+rRCISiUQiViQSiUQkVqwlEYlEIpGIRCKRiEQikUgsiUQiEYlEIpGIRCKRiESiLRIdOqTTe3gPYxgzc5hnwntIp6PMKIoyPuNn/q32n57vGff96cbhTZCvR4Q8THgVhAXyIggL5FkQFsiTICyQR0FYIA+CsEDuBWGB3AnCArkVhAVyIwgL5FoQFsiVICyQS0FYIBeCsEDOBWGBnAnCAjkVhAVyIggL5FgQFsiRICyQQ0FYIAeCsED2BWGB7AnCAtkVhAWyIwgLZFsQFsiWICyQTUFYIBuCsEDWBWGBrAnCAkkJwgJZFYQFsiIIC2RZEBbIkiAskEVBWCALgrBA5gVhgcwJwgKZFYQFMiMIC2RaEBbIlCAskElBWCATgrBAxgVhgYwJwgIZFYQFMiIIC2RYEBbIkCAskEFBWCADgrBA+gVhgfQJwgLpFYQF0iMIC6RbEBZIlyAskE5BWCAdgrBA2gVhgbQJwgJpFYQFkhSEBZIQhAXSIggLJC4IC6RZEBZIkyAskEZBWCANgrBA6gVhgdQJwgKpFYQFUiMIC6RaEBZIlSAskEpBWCAVgrBAYoKwQMoFYYGUCcICKRWEBVIiCAukWBAWSJEgLJBCQVggBYKwQPIFYYHkCcICyRWEBZIjCAskWxAWSJYgLJAgCArkA8aAXLLATgD8AAAAAElFTkSuQmCC"]
    ];

    _.each(testValues, function(value) {
        var cshift = new Webvs.ChannelShift({
            channel: value[0]
        });
        cshift.init(gl, new DummyMain(canvas), new DummyParent(fm));
        fm.setRenderTarget();
        // clear
        gl.clearColor(0,0,0,1);
        gl.clear(gl.COLOR_BUFFER_BIT);
        //draw gradient
        gradientProgram.run(fm, null);
        // run effect
        cshift.update();
        fm.restoreRenderTarget();
        copier.run(null, null, fm.getCurrentTexture());
        cshift.destroy();
        equal(canvas.toDataURL(), value[1], "ChannelShift for " + value[0] + "should be correct");
    });
    gradientProgram.cleanup();

});
